parameters:
    braune_digital_api_base.security.apikey_authenticator.field_name: 'apiKey'

services:
    braune_digital_api_base.security.apikey_authenticator:
        class:  'BrauneDigital\ApiBaseBundle\Security\ApiKeyAuthenticator'
        arguments: ['%braune_digital_api_base.timeout%', '%braune_digital_api_base.security.apikey_authenticator.field_name%']
        public: false

    braune_digital_api_base.security.apikey_user_provider:
        class: 'BrauneDigital\ApiBaseBundle\Security\ApiKeyUserProvider'
        arguments: ['@fos_user.user_manager']
        calls:
            - [setContainer, ['@service_container']]

    braune_digital_api_base.view_response_listener:
        class: 'BrauneDigital\ApiBaseBundle\EventListener\ViewResponseListener'
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 101}

    braune_digital_api_base.event_listener.range_header_listener:
        class: BrauneDigital\ApiBaseBundle\EventListener\RangeHeaderListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }

    braune_digital_api_base.service.token_manager:
        class: 'BrauneDigital\ApiBaseBundle\Service\TokenManager'
        arguments: ['@service_container', '%braune_digital_api_base.security.apikey_authenticator.field_name%']

    braune_digital_api_base.type_extension.form.validator:
        class: 'BrauneDigital\ApiBaseBundle\Form\Extension\Validator\Type\ApiFormTypeValidatorExtension'
        arguments: ['@validator']
        tags:
            - { name: form.type_extension, extended_type: 'Symfony\Component\Form\Extension\Core\Type\FormType'  }

    braune_digital_api_base.validation.group_resolver:
        class: 'BrauneDigital\ApiBaseBundle\Validation\ValidationRequestGroupResolver'
        arguments:
            - "@request_stack"